#ifndef USER_APPS_LIGHT_HOST_CMD_H_
#define USER_APPS_LIGHT_HOST_CMD_H_

typedef enum {
	LIGHT_HOST_CMD_LOAD_CONFIG = 0,
	LIGHT_HOST_CMD_ADD_SLAVE,
	LIGHT_HOST_CMD_RMV_SLAVE,
	LIGHT_HOST_CMD_SET_SEQUENCE,		/// host send duration of GREEN and YELLOW
	LIGHT_HOST_CMD_RESET_DEFALUT,
	LIGHT_HOST_CMD_ONLY_YELLOW,
	LIGHT_HOST_CMD_NUM,
}LIGHT_HOST_CMD;

const char* light_host_cmd[LIGHT_HOST_CMD_NUM] = {
	"LOAD_CONFIG",
	"ADD_SLAVE",
	"RMV_SLAVE",
	"SET_SEQUENCE",
	"RESET_DEFALUT",
	"ONLY_YELLOW",
};


#endif /* USER_APPS_LIGHT_HOST_CMD_H_ */
